'use strict';

import showPhone from './modules/showPhone';
import menu from './modules/menu';
import popupRepair from './modules/popupRepair';
// import checkPhoneInput from './modules/maskPhone';
import popupPrivacy from './modules/popupPrivacy';
import showPrompt from './modules/showPrompt';
import sliderRepair from './modules/sliderRepair';
import agreementSlider from './modules/agreementSlider';
import sliderDesigner from './modules/sliderDesigner';
import showPromptProblem from './modules/showPromptProblem';
import popupConsultation from './modules/popupConsultation';
import getAccordion from './modules/getAccordion';
import getTabWork from './modules/getTabWork';
import sliderFeedback from './modules/sliderFeedback';

showPhone();
menu();
popupRepair();
// checkPhoneInput();
popupPrivacy();
showPrompt();
sliderRepair();
agreementSlider();
sliderDesigner();
showPromptProblem();
popupConsultation();
getAccordion();
getTabWork();
sliderFeedback();